# Generated by Django 5.2.4 on 2025-07-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_end_date_delete_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='end_date',
        ),
    ]
